### ISSUE TITLE
Guarantee order of XML rep of hashtables, or, make tests order-independent?

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/flexpr#2]
As discovered when implementing #1 the hash table implementation has changed on Racket HEAD. The current tests wrongly assume an order that is not guaranteed.

Should rewrite using e.g. `check-match` with `list-no-order`.

**Comment by greghendershott** [comment]
I see two ways to resolve this.
1. Continue to write the xexprs using the `in-hash` order, which is not guaranteed and in fact changes in Racket HEAD. Fix the tests to do an expected vs. actual equality test independent of the order of elements.  (My first instinct, in my comment above.)
2. Write the xexprs in a guaranteed order, for example `(for/list ([k (in-list (sort (hash-keys ht) symbol<?))]) ....`. Adjust the tests' expected output to be sorted like this.

I'm leaning against 1 and toward 2. One reason is that it's a PITA to write such an order-independent comparison for the test. Although that's just my problem, in a similar vein there's a broader problem:

In the real world people sometimes parse XML poorly. They use regular expressions. Or they might parse `xexpr`s using `match`, expecting a fixed order (much like my original tests). Is that truly the correct way? No, not really. Does it actually happen? All? The? Time? Of course it does. Therefore if someone used this library for a web API, and the XML output order changed with a new version of Racket? The output would be theoretically correct, but practically broken.

So I'm leaning toward 2. As a simple example:

```
(flexpr->xexpr '(hasheq 'a 1 'c 3 'b 2))
```

Would now be guaranteed to produce:

```
'(Response () (a () "1") (b () "2") (c () "3"))
```

This would be true for old Rackets, Racket on HEAD, and any future Racket implementation of hash tables.

---

I have a commit, not yet pushed, to do this. Before I do, any feedback @jackfirth ?

**Comment by jackfirth** [comment]
Given that flexprs are constrained to only have symbols as keys, I think it would be less of an issue to sort by key than with generic dictionaries. I would recommend not documenting the exact sorting method used, only promising that the output is deterministic and will not change without a corresponding change in the version of this library used (even if different Racket versions are used).

**Comment by jackfirth** [comment]
I should clarify: Sort them, rely on that in tests, document that the keys will always be in the same order unless you change the library version used, don't document that the order they come in is sorted.

**Comment by greghendershott** [comment]
Thanks for the feedback!

> I would recommend not documenting the exact sorting method used, only promising that the output is deterministic and will not change without a corresponding change in the version of this library used (even if different Racket versions are used).

I agree. The important point isn't the method used per se, it's that the output order won't change in the future.

> I should clarify: Sort them, rely on that in tests, document that the keys will always be in the same order unless you change the library used, don't document that the order they come in is sorted.

I was _pretty_ sure that's what you meant, but thanks for confirming.
