### ISSUE TITLE
Optional "clever" singular symbol function

### ISSUE THREAD

**Issue by jackfirth** [greghendershott/flexpr#3]
The default-singular-symbol function is great for most use cases and very easy to reason about. It would be nice to have a function available (not as the default) that tries to be a bit more "magic", for instance:
- "ves" -> "f" or "fe", e.g. Wolves -> Wolf, Lives -> Life
- "ses" -> "s" or "sis", e.g. Buses -> Bus, Analyses -> Analysis
- "ies" -> "y", e.g. Cities -> City
- "oes" -> "o", e.g. Potatoes -> Potato
- "i" -> "us", e.g. Cacti -> Cactus
- "a" -> "on", e.g. Phenomena -> Phenomenon

This is tricky because some are ambiguous, not to mention irregular words like "fish" and "children". Those could probably be ignored or default to the one used in the majority of cases. Or this could just be way too much work to do at all. But it _would_ be cool.

**Comment by greghendershott** [comment]
It would definitely be cool to have, somewhere. A few off-the-cuff thoughts:
- It might deserve to be its own package?
- Rules might not be enough, it may need data?
  - There might be freely usable static, hand-made dictionaries?
  - There might be dictionaries created from crawling and doing stats, as with natural language translation?  (You may have some new colleagues in that space. :) )

**Comment by jackfirth** [comment]
I like the idea of some `plural` package that provides some functions specifically for pluralizing and singularizing English words. Then this would be a breeze (though it may be good to make it _another_ `flexpr-plural` package to avoid a dependency on some package that includes a humongous dictionary of special cases).

(Perhaps I should ask the Google Brain team to do this ;) )

**Comment by greghendershott** [comment]
> Then this would be a breeze (though it may be good to make it another flexpr-plural package to avoid a dependency on some package that includes a humongous dictionary of special cases).

Well, I think one `flexpr` and one `plural` package is probably enough. I don't think it would be too inconvenient for someone to define their own `current-singular-symbol` function using `plural`, to supply to `flexpr`.

Anyway I think we're like that SNL skit where the barbers with no customers give each other haircuts all day.  IOW if/when there are more (any?) people using this for real stuff, I'm sure they'll let us know about any pain points. :grin:

**Comment by jackfirth** [comment]
> > Then this would be a breeze (though it may be good to make it another flexpr-plural package to avoid a dependency on some package that includes a humongous dictionary of special cases).
> 
> Well, I think one flexpr and one plural package is probably enough. I don't think it would be too inconvenient for someone to define their own current-singular-symbol function using plural, to supply to flexpr.

That makes sense, it is an awful lot of maintenance and setup work for something so trivial.

> Anyway I think we're like that SNL skit where the barbers with no customers give each other haircuts all day. IOW if/when there are more (any?) people using this for real stuff, I'm sure they'll let us know about any pain points. :grin:

I'm actually in the process of drafting a 24 Days of Racket Packages blog post using this package, so you may get more users rather soon ;). The draft is available as [this gist](https://gist.github.com/jackfirth/3d487c930b05a1213d41), comments, edits, and reviews are more than welcome.

**Comment by greghendershott** [comment]
> I'm actually in the process of drafting a 24 Days of Racket Packages blog post using this package, so you may get more users rather soon ;). The draft is available as this gist, comments, edits, and reviews are more than welcome.

Oh cool you're doing that. I got as far as picking a couple dozen packages, writing up a few of them, then realizing I don't have time now to finish.

I'll take a look at your gist when I have time.
