### ISSUE TITLE
`read` / `write` functions and variants

### ISSUE THREAD

**Issue by jackfirth** [greghendershott/flexpr#4]
When working with ports, it's common for code to use things like with-output-to-file to change the current input or output ports and then rely on read, write, display, print, etc. for IO. When doing that with flexprs, it might be nice to have shorthands like `write-flexpr-json` and `write-flexpr-xml` in a manner similar to the current `json` library.

**Comment by greghendershott** [comment]
Do you mean providing a couple pre-made function compositions, which do what is shown in the main scribble doc example? Such as:

```
;;; Convenience: write flavors

(define write-flexpr-xml  (compose display-xml/content xexpr->xml flexpr->xexpr))
(define write-flexpr-json (compose write-json flexpr->jsexpr))
```

**Comment by greghendershott** [comment]
OK it can't be quite _that_ simple as using `compose`, due to extra parameters for e.g. `write-json`.

Which is a point in favor of this package defining and providing these.

**Comment by greghendershott** [comment]
Also there should probably be both `display-xml` and `write-xml` variants.  IME most web services tend to return nicely indented XML, as done by `display-xml`.

(OK, they also tend to return pretty printed JSON. But there is no `display-json` like that, and I'm not about to detour to do that now, much less in this package. :D )

I think I'm almost ready to commit, push, close this.

**Comment by jackfirth** [comment]
Great! Though the `/content` suffix looks a bit odd to me, what do you think?  Looking through the `xml` docs again, I noticed there's a `write-xexpr` variant that's closer to `write-flexpr-xml` than `write-xml/content` is. Would it make sense to break away from the xml `/content` suffix pattern?

**Comment by greghendershott** [comment]
Although it does look a bit odd, my thinking:
- It makes it clearer that these thinly wrap `display-xml/content` and `write-xml/content` -- not `display-xml` and `write-xml`.
- If it were to make sense (?) to wrap those latter someday, too, it wouldn't be confusing. The name wouldn't need to something like `display-xml/not-content` or `display-xml/oh-shit-I-already-used-up-the-good-name-for-this-O_o`.  Even though it would be fun to use `O_o` in an identifier.

**Comment by jackfirth** [comment]
I can see that. I'll learn to get used to it then :grin:

**Comment by greghendershott** [comment]
If you find it too ugly there's always the `rename-in` form for `require`.

Hmm, actually: You know how there's a `prefix-in` form to add a prefix?  You could make a new package that provides a form to do the opposite, remove a suffix (if any). `(require (drop-suffix-in "/content" flexpr))`. That would be some mighty fine yak shaving. ;)

Oh wait, `filtered-in` can already do tricks like this. Wow.

**Comment by jackfirth** [comment]
Wow indeed, I didn't know about `filtered-in`. That's pretty crazy.
