### ISSUE TITLE
YAML?

### ISSUE THREAD

**Issue by jackfirth** [greghendershott/flexpr#5]
Given that there's [an excellent YAML package](http://pkg-build.racket-lang.org/doc/yaml/index.html), would it make sense to support conversions from `flexpr`s to `yaml?` values? I think the only real change needed is to change from `hasheq`s to `hash`es when converting, but I haven't thought about it too much.

**Comment by greghendershott** [comment]
I don't think so. I had in mind a specific use-case for this package: Creating web service responses that can be either JSON or XML.

In 2015 AFAICT the story is "return JSON", period -- or maybe "return JSON by default, and if not too much trouble offer a choice of XML". This package is supposed to address the "if not too much trouble" part.

I haven't seen a web service return YAML, even optionally (although I suppose there's a counter-example).

So I'm not sure it's worth writing/testing the code (however simple), and adding a dep on another package (however heavy or light, I don't know), to address a use-case I don't see?

Instead this might be the sort of feature that should be done only JIT -- if/when it matters enough to someone?

**Comment by jackfirth** [comment]
That makes sense.  This would more be useful if this library was being used for configuration file formats, there YAML is used about as often as JSON and XML. But when dealing specifically with web services it wouldn't be terribly useful.

**Comment by greghendershott** [comment]
Closing because not actionable in the foreseeable future.
