### ISSUE TITLE
Nondeterministic hash-table order for JSON

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/flexpr#7]
On `#racket` @samth pointed out:

```
11:01 AM <samth> greghendershott: your flexpr pkg has a dependency on hash-table ordering in the tests
11:01 AM <samth> for the string output via json
11:02 AM <samth> which broke on the tests for the next release
11:06 AM <greghendershott> samth: Hmm sounds like https://github.com/greghendershott/flexpr/issues/2 not actually fixed. Will need to dig in. thx for heads up
11:07 AM <samth> greghendershott: that seems to be about xexprs
11:07 AM <samth> whereas the failing test is basically the same thing, but for json
11:33 AM <greghendershott> samth: I'm curious why the JSON tests did pass, before -- on the same Racket HEAD where the XML ones did not
11:33 AM <greghendershott> https://travis-ci.org/greghendershott/flexpr/jobs/86759873
11:33 AM <samth> greghendershott: depends what order the hash table gets traversed in
11:34 AM <samth> it'll pass on some machines, not on others, or with some versions of racket and not others
11:34 AM <samth> the tests pass fine on my laptop
```

So same issue as #2.  But maybe different resolution.

With XML the output is not really expressed as a hash-table, it's a tree. The concern is that people sometimes parse XML expecting a certain order.  So there was a rationale for making the XML output order predictable.

With JSON, the output is expressed as a hash-table and people consume it as such. As a result the better approach here might be to leave the output as-is (order of elements is not guaranteed) and instead to make the tests themselves order-independent.

**Comment by samth** [comment]
Maybe the easiest way to fix the tests is to write the data, read it back with `read-json`, and then check that you got what you expect.
